# Generated by Django 5.1.1 on 2025-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
